name: ci

on:
  pull_request:

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - run: uvx tox -elinters

  py:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: uvx tox -epy
